package cooperation.qlink;

public abstract interface QlinkConst
{
  public static final int A = 4;
  public static final String A = "param.headpath";
  public static final int B = 5;
  public static final String B = "param.transprogress";
  public static final int C = 6;
  public static final String C = "param.transspeed";
  public static final int D = 7;
  public static final String D = "param.transresult";
  public static final int E = 8;
  public static final String E = "param.transfailedcode";
  public static final int F = 9;
  public static final String F = "param.transextfailedcode";
  public static final int G = 10;
  public static final String G = "param.msgrecord";
  public static final int H = 11;
  public static final String H = "param.filemd5";
  public static final int I = 12;
  public static final String I = "param.sendfilemsgresult";
  public static final int J = 13;
  public static final String J = "param.isnewmsg";
  public static final int K = 14;
  public static final String K = "param.transfilepath";
  public static final int L = 15;
  public static final String L = "param.transisthumb";
  public static final int M = 16;
  public static final String M = "param.cookie";
  public static final int N = 17;
  public static final String N = "param.msgcontent";
  public static final int O = 3;
  public static final String O = "param.tempsignature";
  public static final int P = 10;
  public static final String P = "param.refusemsg";
  public static final String Q = "param.newmsgneeddata";
  public static final String R = "param.reportnbinfotype";
  public static final String S = "param.reportnbinfo";
  public static final String T = "param.tempsign";
  public static final String U = "param.fromuin";
  public static final String V = "param.touin";
  public static final String W = "param.transpjspeed";
  public static final String X = "param.transinspeed";
  public static final String Y = "param.transoutspeed";
  public static final String Z = "param.transssid";
  public static final int a = 3;
  public static final long a = 480000L;
  public static final String a = "cmd.sendfilemsg";
  public static final String aa = "param.qquins";
  public static final String ab = "param.transextrainfo";
  public static final String ac = "param.insertfileinfo";
  public static final String ad = "[QLINK]-QQ ";
  public static final String ae = "QLINK_";
  public static final String af = "QLINK_";
  public static final String ag = "string_from";
  public static final String ah = "string_uin";
  public static final String ai = "string_nick";
  public static final String aj = "string_bundle";
  public static final String ak = "string_filepaths";
  public static final String al = "STRING_CONTINUE_SEND_TO_";
  public static final String am = "string_beforeshare_selectedfile_count";
  public static final String an = "qqf2f://qf/";
  public static final String ao = "i=";
  public static final String ap = "u=";
  public static final String aq = "n=";
  public static final String ar = "o=";
  public static final String as = "k=";
  public static final String at = "p=";
  public static final int b = 4;
  public static final long b = 480000L;
  public static final String b = "cmd.exitfilebrowser";
  public static final int c = 5;
  public static final String c = "cmd.sendfilemsgs";
  public static final int d = 6;
  public static final String d = "cmd.sendfilemsgsrsp";
  public static final int e = 7;
  public static final String e = "cmd.recvfilemsg";
  public static final int f = 8;
  public static final String f = "cmd.onpushmsg";
  public static final int g = 9;
  public static final String g = "cmd.onpushnotifylistmsg";
  public static final int h = 10;
  public static final String h = "cmd.sendcontacthead";
  public static final int i = 12;
  public static final String i = "cmd.recvunrecvfilemsg";
  public static final int j = 13;
  public static final String j = "cmd.sendmsgrecord";
  public static final int k = 14;
  public static final String k = "cmd.canceltans";
  public static final int l = 15;
  public static final String l = "cmd.isnewmsg";
  public static final int m = 16;
  public static final String m = "cmd.discardsendmsg";
  public static final int n = 17;
  public static final String n = "cmd.senduserinfo";
  public static final int o = 18;
  public static final String o = "cmd.senddailogclickinfo";
  public static final int p = 19;
  public static final String p = "cmd.sendheart";
  public static final int q = 20;
  public static final String q = "cmd.sendsimplecmd";
  public static final int r = 21;
  public static final String r = "param.uin";
  public static final int s = 22;
  public static final String s = "param.filepath";
  public static final int t = 23;
  public static final String t = "param.sessionid";
  public static final int u = 24;
  public static final String u = "param.sendfilefileinfo";
  public static final int v = 25;
  public static final String v = "param.sendfilefileinfos";
  public static final int w = 10;
  public static final String w = "param.sendfilefilenbyinfo";
  public static final int x = 1;
  public static final String x = "param.recvfilefilenbyinfo";
  public static final int y = 2;
  public static final String y = "param.msgstatus";
  public static final int z = 3;
  public static final String z = "param.msgstatuserrcode";
}


/* Location:              E:\apk\QQ_91\classes2-dex2jar.jar!\cooperation\qlink\QlinkConst.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       0.7.1
 */