package com.tencent.device.utils;

public abstract interface SmartDeviceReport$ActionName
{
  public static final String A = "Usr_Device_Sell";
  public static final String B = "Usr_Share_Page";
  public static final String C = "Usr_Share_AddDel";
  public static final String D = "Usr_Share_Confirm";
  public static final String E = "Usr_Share_Legal";
  public static final String F = "Usr_Share_LegalButton";
  public static final String G = "Usr_Share_Button";
  public static final String H = "Usr_MsgMgr_Open";
  public static final String I = "Usr_MsgMgr_Setting";
  public static final String J = "Usr_TV_Video";
  public static final String K = "Net_Tinyid";
  public static final String L = "Net_Reg_MidSrv";
  public static final String M = "Net_Reg_Router";
  public static final String N = "Net_Reg_BLE";
  public static final String O = "Net_BindDevice";
  public static final String P = "Net_Unbind";
  public static final String Q = "Net_Erase";
  public static final String R = "Net_Recover";
  public static final String S = "Net_CheckReg";
  public static final String T = "Net_CheckRegInfo";
  public static final String U = "Net_FetchDeviceList";
  public static final String V = "Net_FetchOnlineStatus";
  public static final String W = "Net_FetchProductInfo";
  public static final String X = "Net_SetRemark";
  public static final String Y = "Net_FetchBlueToothDeviceSessionKey";
  public static final String Z = "Net_FetchBlueToothDeviceInfo";
  public static final String a = "User_BindDev";
  public static final String aA = "Usr_Enable_Device";
  public static final String aB = "Usr_Show_WifiConfig_UI";
  public static final String aC = "Usr_WifiConfig";
  public static final String aD = "Usr_WifiConfig_Retry";
  public static final String aE = "Usr_Show_Bind_Activity_UI";
  public static final String aF = "Usr_Bind_Activity";
  public static final String aG = "Net_Bind_BLE_Search";
  public static final String aH = "Net_Bind_BLE_Connect";
  public static final String aI = "Net_Fetch_BLE_SessionKey";
  public static final String aJ = "Net_Fetch_BLE_License";
  public static final String aK = "Net_BLE_Write_Back";
  public static final String aL = "Net_SearchDevice_Result";
  public static final String aM = "Net_SearchDevice_DeviceItem";
  public static final String aN = "Net_Wifi_Config_Time_Used";
  public static final String aO = "Net_Wifi_Config_Ack_Time_Used";
  public static final String aP = "Net_SearchDevice_Retry";
  public static final String aQ = "Net_SearchDevice_Back";
  public static final String aR = "Usr_WifiRouter_Net";
  public static final String aS = "Usr_WifiConfig_Reset";
  public static final String aT = "Usr_VoiceLink_Action";
  public static final String aU = "Net_Bind_BLE_Scan_Time_Used";
  public static final String aV = "Net_Bind_BLE_Connect_Time_Used";
  public static final String aW = "Usr_CloudPrint_SendFile";
  public static final String aX = "Usr_CloudPrint_SendPrint";
  public static final String aY = "Usr_IPC_RTMP";
  public static final String aa = "Net_Get_Sharelist";
  public static final String ab = "Net_Get_LiteappSetting";
  public static final String ac = "Usr_Click_MyDevice";
  public static final String ad = "Usr_Bind_Net_Setting";
  public static final String ae = "Usr_BindDevicePage";
  public static final String af = "Usr_AIO_ReceiveMsg";
  public static final String ag = "Usr_AIO_ReceiveMsg_Click";
  public static final String ah = "Usr_QRCode_WifiRoute";
  public static final String ai = "Usr_QRCode_Smartlink";
  public static final String aj = "Usr_AIO_SupportGroupChat";
  public static final String ak = "QFind_BleState";
  public static final String al = "QFind_GPSState";
  public static final String am = "Usr_Publicdevice_Tipoff";
  public static final String an = "Usr_Publicdevice_Share";
  public static final String ao = "Net_PublicCamera_Connect";
  public static final String ap = "Net_PublicCamera_Recv_Data";
  public static final String aq = "Net_Start_Service_Host";
  public static final String ar = "Net_Start_Service_Remote";
  public static final String as = "FR_StrangerComming";
  public static final String at = "FR_RegisterBtnClick";
  public static final String au = "FR_RegisterSucc";
  public static final String av = "QFIND_BluetoothBtnClick";
  public static final String aw = "QFIND_Bluetooth_Status";
  public static final String ax = "Voice_Link_SampleRate";
  public static final String ay = "Usr_Entrance";
  public static final String az = "Usr_Analyze_URL";
  public static final String b = "Usr_AIO_Open";
  public static final String c = "Usr_AIO_Menu";
  public static final String d = "Usr_AIO_SendMsg";
  public static final String e = "Usr_AIO_SendGroupMsg";
  public static final String f = "Usr_NewDevice_Click";
  public static final String g = "Usr_LAN_Search_First";
  public static final String h = "Usr_LAN_Search_Retry";
  public static final String i = "Usr_LAN_Enable";
  public static final String j = "Usr_QRCode";
  public static final String k = "Usr_QRCode_Result";
  public static final String l = "Net_WIFI_Password";
  public static final String m = "Usr_Bind_New";
  public static final String n = "Net_BLE_Connect";
  public static final String o = "Net_BLE_Disconnect";
  public static final String p = "Usr_LiteApp_List";
  public static final String q = "Net_LiteApp_Setting";
  public static final String r = "Usr_LiteApp_Open";
  public static final String s = "Usr_LiteApp_Open_Online";
  public static final String t = "Usr_LiteApp_Menu";
  public static final String u = "Usr_LiteApp_Share";
  public static final String v = "Usr_LiteApp_App";
  public static final String w = "Usr_LiteApp_Remark";
  public static final String x = "Usr_LiteApp_Unbind";
  public static final String y = "Usr_IPC_Open";
  public static final String z = "Usr_IPC_Button";
}


/* Location:              E:\apk\QQ_91\classes5-dex2jar.jar!\com\tencent\device\utils\SmartDeviceReport$ActionName.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       0.7.1
 */