package com.sixgod.pluginsdk.a;

import android.app.Activity;
import android.app.Application;
import android.app.Dialog;
import android.app.Instrumentation;
import android.app.Service;
import android.content.Context;
import android.content.ContextWrapper;
import android.content.Intent;
import android.content.pm.ActivityInfo;
import android.content.pm.ApplicationInfo;
import android.content.res.Configuration;
import android.content.res.Resources.Theme;
import android.os.Bundle;
import android.os.IBinder;
import android.util.DisplayMetrics;
import android.view.ContextThemeWrapper;
import android.view.Window;
import com.sixgod.pluginsdk.common.Constants;
import java.io.File;

public final class a
{
  public g A;
  public g B;
  public g C;
  public g D;
  public g E;
  public g F;
  public g G;
  public g H;
  public g I;
  public g J;
  public g K;
  public g L;
  public g M;
  public g N;
  public g O;
  public g P;
  public g Q;
  public g R;
  public g S;
  public g T;
  public g U;
  public g V;
  public g W;
  public g X;
  public g Y;
  public g Z;
  public d a;
  public f aA;
  public f aB;
  public f aC;
  public f aD;
  public f aE;
  public f aF;
  public f aG;
  public f aH;
  public f aI;
  public f aJ;
  public f aK;
  public f aL;
  public f aM;
  public f aN;
  public f aO;
  public f aP;
  public f aQ;
  public f aR;
  public f aS;
  public f aT;
  public f aU;
  public f aV;
  public f aW;
  public f aX;
  public f aY;
  public f aZ;
  public g aa;
  public g ab;
  public g ac;
  public g ad;
  public g ae;
  public g af;
  public g ag;
  public e ah;
  public e ai;
  public e aj;
  public e ak;
  public e al;
  public e am;
  public e an;
  public e ao;
  public e ap;
  public e aq;
  public f ar;
  public f as;
  public f at;
  public f au;
  public f av;
  public f aw;
  public f ax;
  public f ay;
  public f az;
  public d b;
  public f ba;
  public f bb;
  public f bc;
  public f bd;
  public f be;
  public f bf;
  public f bg;
  public f bh;
  public f bi;
  public f bj;
  public f bk;
  public f bl;
  protected ClassLoader bm;
  public f bn;
  public f bo;
  public f bp;
  public f bq;
  public f br;
  public d c;
  public d d;
  public d e;
  public d f;
  public d g;
  public d h;
  public d i;
  public d j;
  public d k;
  public d l;
  public d m;
  public d n;
  public d o;
  public d p;
  public g q;
  public g r;
  public g s;
  public g t;
  public g u;
  public g v;
  public g w;
  public g x;
  public g y;
  public g z;
  
  public a(ClassLoader paramClassLoader)
  {
    this.bm = paramClassLoader;
    this.a = new d(this.bm, "android.content.pm.PackageParser");
    this.b = new d(this.bm, "android.content.pm.PackageParser$Package");
    this.c = new d(this.bm, "android.content.pm.PackageParser$Activity");
    this.d = new d(this.bm, "android.content.pm.PackageParser$Provider");
    this.o = new d(this.bm, "android.content.pm.PackageParser$Instrumentation");
    this.p = new d(this.bm, "android.content.pm.PackageParser$Permission");
    this.e = new d(this.bm, "android.content.pm.PackageParser$Service");
    this.f = new d(this.bm, "android.app.LoadedApk");
    this.g = new d(this.bm, "android.app.ActivityThread");
    this.h = new d(this.bm, "android.content.res.CompatibilityInfo");
    this.i = new d(this.bm, "android.app.Activity$NonConfigurationInstances");
    this.j = new d(this.bm, "android.app.ContextImpl");
    if (this.j.b == null) {
      this.j = new d(this.bm, "android.app.ApplicationContext");
    }
    this.k = new d(this.bm, "android.content.pm.PackageParser$ActivityIntentInfo");
    this.l = new d(this.bm, "android.content.pm.PackageParser$Component");
    this.m = new d(this.bm, "com.android.internal.app.IVoiceInteractor");
    this.n = new d(this.bm, "android.app.Application");
    this.q = new g(this.a.b, "parsePackage", new Class[] { File.class, String.class, DisplayMetrics.class, Integer.TYPE });
    this.r = new g(this.a.b, "parsePackage", new Class[] { File.class, Integer.TYPE });
    this.ae = new g(this.a.b, "collectCertificates", new Class[] { this.b.b, Integer.TYPE });
    this.s = new g(this.g.b, "currentActivityThread", null);
    this.v = new g(Activity.class, "performRestart", null);
    this.u = new g(Activity.class, "performResume", null);
    this.t = new g(Activity.class, "performStart", null);
    this.w = new g(Activity.class, "performStop", null);
    this.x = new g(Activity.class, "onNewIntent", new Class[] { Intent.class });
    this.y = new g(Activity.class, "onSaveInstanceState", new Class[] { Bundle.class });
    this.z = new g(Activity.class, "onPause", null);
    this.A = new g(Activity.class, "performPause", null);
    this.B = new g(Activity.class, "onUserLeaveHint", null);
    this.C = new g(Activity.class, "onDestroy", null);
    this.D = new g(Activity.class, "performDestroy", null);
    this.F = new g(Activity.class, "onCreateDialog", new Class[] { Integer.TYPE });
    this.G = new g(Activity.class, "onPrepareDialog", new Class[] { Integer.TYPE, Dialog.class });
    this.H = new g(Activity.class, "onApplyThemeResource", new Class[] { Resources.Theme.class, Integer.TYPE, Boolean.TYPE });
    this.I = new g(Activity.class, "onActivityResult", new Class[] { Integer.TYPE, Integer.TYPE, Intent.class });
    this.J = new g(Activity.class, "onTitleChanged", new Class[] { CharSequence.class, Integer.TYPE });
    this.K = new g(Activity.class, "onChildTitleChanged", new Class[] { Activity.class, CharSequence.class });
    this.L = new g(Activity.class, "setParent", new Class[] { Activity.class });
    this.X = new g(Activity.class, "attach", new Class[] { Context.class, this.g.b, Instrumentation.class, IBinder.class, Application.class, Intent.class, ActivityInfo.class, CharSequence.class, Activity.class, String.class, Object.class, Configuration.class });
    this.Y = new g(Activity.class, "attach", new Class[] { Context.class, this.g.b, Instrumentation.class, IBinder.class, Application.class, Intent.class, ActivityInfo.class, CharSequence.class, Activity.class, String.class, this.i.b, Configuration.class });
    if (this.m.a)
    {
      this.Z = new g(Activity.class, "attach", new Class[] { Context.class, this.g.b, Instrumentation.class, IBinder.class, Integer.TYPE, Application.class, Intent.class, ActivityInfo.class, CharSequence.class, Activity.class, String.class, this.i.b, Configuration.class, this.m.b });
      this.aa = new g(Activity.class, "attach", new Class[] { Context.class, this.g.b, Instrumentation.class, IBinder.class, Integer.TYPE, Application.class, Intent.class, ActivityInfo.class, CharSequence.class, Activity.class, String.class, this.i.b, Configuration.class, String.class, this.m.b });
      this.ab = new g(Activity.class, "attach", new Class[] { Context.class, this.g.b, Instrumentation.class, IBinder.class, Integer.TYPE, Application.class, Intent.class, ActivityInfo.class, CharSequence.class, Activity.class, String.class, this.i.b, Configuration.class, String.class, this.m.b, Window.class });
    }
    this.E = new g(Activity.class, "onPostCreate", new Class[] { Bundle.class });
    this.af = new g(Activity.class, "initActionBar", null);
    this.ag = new g(Activity.class, "initWindowDecorActionBar", null);
    this.M = new g(this.j.b, "init", new Class[] { this.f.b, IBinder.class, this.g.b });
    this.R = new g(this.j.b, "createAppContext", new Class[] { this.g.b, this.f.b });
    this.S = new g(this.j.b, "createActivityContext", new Class[] { this.g.b, this.f.b, IBinder.class });
    this.T = new g(this.j.b, "createActivityContext", new Class[] { this.g.b, this.f.b, Integer.TYPE, Configuration.class });
    this.U = new g(this.j.b, "createActivityContext", new Class[] { this.g.b, this.f.b, IBinder.class, Integer.TYPE, Configuration.class });
    this.N = new g(this.j.b, "setOuterContext", new Class[] { Context.class });
    this.W = new g(this.j.b, "getPackageManager", null);
    this.O = new g(Service.class, "attach", new Class[] { Context.class, this.g.b, String.class, IBinder.class, Application.class, Object.class });
    this.P = new g(Instrumentation.class, "newApplication", new Class[] { ClassLoader.class, String.class, Context.class });
    this.V = new g(Instrumentation.class, "newActivity", new Class[] { ClassLoader.class, String.class, Intent.class });
    this.ad = new g(Instrumentation.class, "callActivityOnCreate", new Class[] { Activity.class, Bundle.class });
    this.ac = new g(this.f.b, "makeApplication", new Class[] { Boolean.TYPE, Instrumentation.class });
    this.Q = new g(Application.class, "attach", new Class[] { Context.class });
    this.ah = new e(this.a, new Class[] { String.class });
    this.ai = new e(this.a, null);
    paramClassLoader = this.g.b;
    Class localClass1 = this.g.b;
    Class localClass2 = Boolean.TYPE;
    Class localClass3 = Boolean.TYPE;
    this.aj = new e(this.f, new Class[] { paramClassLoader, ApplicationInfo.class, localClass1, ClassLoader.class, localClass2, localClass3 });
    paramClassLoader = this.g.b;
    this.an = new e(this.f, new Class[] { paramClassLoader, String.class, Context.class, ApplicationInfo.class });
    paramClassLoader = this.g.b;
    localClass1 = this.h.b;
    localClass2 = Boolean.TYPE;
    localClass3 = Boolean.TYPE;
    this.ak = new e(this.f, new Class[] { paramClassLoader, ApplicationInfo.class, localClass1, ClassLoader.class, localClass2, localClass3 });
    paramClassLoader = this.g.b;
    this.ao = new e(this.f, new Class[] { paramClassLoader });
    paramClassLoader = this.g.b;
    localClass1 = this.h.b;
    localClass2 = this.g.b;
    localClass3 = Boolean.TYPE;
    Class localClass4 = Boolean.TYPE;
    this.al = new e(this.f, new Class[] { paramClassLoader, ApplicationInfo.class, localClass1, localClass2, ClassLoader.class, localClass3, localClass4 });
    paramClassLoader = this.g.b;
    localClass1 = this.h.b;
    this.ap = new e(this.f, new Class[] { paramClassLoader, String.class, Context.class, ApplicationInfo.class, localClass1 });
    paramClassLoader = this.g.b;
    localClass1 = this.h.b;
    localClass2 = Boolean.TYPE;
    localClass3 = Boolean.TYPE;
    localClass4 = Boolean.TYPE;
    this.am = new e(this.f, new Class[] { paramClassLoader, ApplicationInfo.class, localClass1, ClassLoader.class, localClass2, localClass3, localClass4 });
    this.aq = new e(this.j, null);
    this.ar = new f(this.b.b, "applicationInfo");
    this.as = new f(ApplicationInfo.class, "sourceDir");
    this.at = new f(Activity.class, "mMainThread");
    this.au = new f(this.f.b, "mClassLoader");
    this.av = new f(this.f.b, "mResDir");
    this.bn = new f(this.f.b, "mAppDir");
    this.bo = new f(this.f.b, "mDataDir");
    this.bp = new f(this.f.b, "mDataDirFile");
    this.bq = new f(this.f.b, "mLibDir");
    this.aw = new f(this.f.b, "mPackageName");
    this.aN = new f(this.f.b, "mResources");
    this.bg = new f(this.f.b, "mApplication");
    this.br = new f(this.f.b, "mApplicationInfo");
    this.aO = new f(this.j.b, "mResources");
    this.aP = new f(ContextThemeWrapper.class, "mResources");
    this.ax = new f(this.g.b, "mPackages");
    this.ay = new f(this.b.b, "activities");
    this.az = new f(this.b.b, "services");
    this.aA = new f(this.b.b, "providers");
    this.aB = new f(this.b.b, "permissions");
    this.aJ = new f(this.b.b, "instrumentation");
    this.aK = new f(this.b.b, "requestedPermissions");
    this.aL = new f(this.b.b, "configPreferences");
    this.aM = new f(this.b.b, "reqFeatures");
    this.aC = new f(this.c.b, "info");
    this.aD = new f(this.e.b, "info");
    this.aQ = new f(Activity.class, "mResultCode");
    this.aR = new f(Activity.class, "mResultData");
    this.aS = new f(this.g.b, "mAllApplications");
    this.aT = new f(this.g.b, "mInstrumentation");
    this.aU = new f(ContextWrapper.class, "mBase");
    this.aV = new f(ContextThemeWrapper.class, "mBase");
    this.aW = new f(this.c.b, "intents");
    this.aX = new f(this.k.b, "mCategories");
    this.aY = new f(this.l.b, "intents");
    this.aZ = new f(this.b.b, "receivers");
    this.ba = new f(Activity.class, "mToken");
    this.bb = new f(Service.class, "mToken");
    localClass1 = this.g.b;
    if (Constants.ANDROID_VERSION <= 10) {}
    for (paramClassLoader = "mConfiguration";; paramClassLoader = "mCompatConfiguration")
    {
      this.bc = new f(localClass1, paramClassLoader);
      this.bd = new f(Activity.class, "mStartedActivity");
      this.be = new f(Activity.class, "mCalled");
      if (Constants.ANDROID_VERSION > 10) {
        this.bf = new f(this.j.b, "mBasePackageName");
      }
      this.bh = new f(this.b.b, "mSignatures");
      this.aE = new f(this.b.b, "mVersionCode");
      this.aF = new f(this.b.b, "mVersionName");
      this.aG = new f(this.b.b, "mSharedUserId");
      this.aH = new f(this.b.b, "mSharedUserLabel");
      this.aI = new f(this.b.b, "mAppMetaData");
      this.bi = new f(this.n.b, "mLoadedApk");
      this.bj = new f(this.d.b, "info");
      this.bk = new f(this.o.b, "info");
      this.bl = new f(this.p.b, "info");
      return;
    }
  }
}


/* Location:              E:\apk\QQ_91\classes3-dex2jar.jar!\com\sixgod\pluginsdk\a\a.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       0.7.1
 */