package com.tencent.mobileqq.shortvideo;

public abstract interface ShortVideoConstants
{
  public static final int A = 160;
  public static final String A = "file_name";
  public static final int B = 100;
  public static final String B = "file_format";
  public static final int C = 80;
  public static final String C = "file_uuid";
  public static final int D = 1;
  public static final String D = "from_uin_type";
  public static final int E = 2;
  public static final String E = "from_session_uin";
  public static final int F = 3;
  public static final String F = "to_uin_type";
  public static final int G = 4;
  public static final String G = "from_busi_type";
  public static final int H = 5;
  public static final String H = "to_busi_type";
  public static final int I = 6;
  public static final String I = "from_uin";
  public static final int J = 7;
  public static final String J = "is_from_system_media";
  public static final int K = 8;
  public static final String K = "is_forward_ptv";
  public static final String L = "video_url";
  public static final String M = "message_click_start";
  public static final String N = "video_play_caller";
  public static final String O = "struct_msg_video_info";
  public static final String P = "sv_total_frame_count";
  public static final String Q = "sv_total_record_time";
  public static final String R = "sv_encode_max_bitrate";
  public static final String S = "sv_encode_min_bitrate";
  public static final String T = "sv_encode_qmax";
  public static final String U = "sv_encode_qmin";
  public static final String V = "sv_encode_qmaxdiff";
  public static final String W = "sv_encode_ref_frame";
  public static final String X = "sv_encode_smooth";
  public static final String Y = "sv_encode_totaltime_adjust";
  public static final String Z = "sv_encode_timestamp_fix";
  public static final float a = 2.0F;
  public static final int a = 60;
  public static final String a = "ShortVideo.TAG";
  public static final String aa = "sv_encode_bless_audio_time_low";
  public static final String ab = "sv_encode_bless_audio_time_high";
  public static final String ac = "sv_encode_bless_audio_time_ratio";
  public static final String ad = "sv_encode_baseline_mp4";
  public static final String ae = "video_mood_content";
  public static final String af = "video_mood_priv";
  public static final String ag = "video_mood_privUinList";
  public static final String ah = "enable_edit_video";
  public static final String ai = "[视频]";
  public static final String aj = "[视频对讲]";
  public static final String ak = "key_check_temp";
  public static final String al = "bless_uin_list";
  public static final String am = "is_existed_bless_ptv";
  public static final String an = "existed_bless_ptv_msgdata";
  public static final String ao = "bless_ptv_mp4_path";
  public static final String ap = "encode_video_params";
  public static final String c = "local_media_id";
  public static final long d = 28835840L;
  public static final String d = "file_send_size";
  public static final String e = "file_send_business_type";
  public static final String f = "file_send_duration";
  public static final String g = "file_send_path";
  public static final String h = "file_video_source_dir";
  public static final String i = "thumbfile_send_path";
  public static final String j = "file_shortvideo_md5";
  public static final String k = "file_shortvideo_local_md5";
  public static final String l = "file_is_merged_local";
  public static final int l_ = 0;
  public static final String m = "thumbfile_send_width";
  public static final int m_ = 1;
  public static final String n = "thumbfile_send_height";
  public static final int n_ = 2;
  public static final int o = 1003;
  public static final String o = "thumbfile_md5";
  public static final int o_ = 3;
  public static final int p = 1004;
  public static final String p = "key_message_for_shortvideo";
  public static final int p_ = 1001;
  public static final int q = 1005;
  public static final String q = "support_progressive";
  public static final int q_ = 1002;
  public static final int r = 1006;
  public static final String r = "file_width";
  public static final int s = 320;
  public static final String s = "file_height";
  public static final int t = 240;
  public static final String t = "start_init_activity_after_sended";
  public static final int u = 100;
  public static final String u = "activity_before_enter_send_video";
  public static final int v = 100;
  public static final String v = "file_source";
  public static final int w = 240;
  public static final String w = "camera";
  public static final int x = 240;
  public static final String x = "album";
  public static final int y = 160;
  public static final String y = "album_flow";
  public static final int z = 160;
  public static final String z = "file_thumb_Size";
}


/* Location:              E:\apk\QQ_91\classes5-dex2jar.jar!\com\tencent\mobileqq\shortvideo\ShortVideoConstants.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       0.7.1
 */